//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18034
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS3TrophyIsGood.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PS3TrophyIsGood.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Can&apos;t find game..
        /// </summary>
        internal static string CantFindGame {
            get {
                return ResourceManager.GetString("CantFindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You can&apos;t lock other thropy when platinum is locked. 的當地語系化字串。
        /// </summary>
        internal static string CantLoclPlatinumBeforOther {
            get {
                return ResourceManager.GetString("CantLoclPlatinumBeforOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You can&apos;t unlock platinum when other thropy is unlocked. 的當地語系化字串。
        /// </summary>
        internal static string CantUnloclPlatinumBeforOther {
            get {
                return ResourceManager.GetString("CantUnloclPlatinumBeforOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The file has not been saved,  save it? 的當地語系化字串。
        /// </summary>
        internal static string CloseConfirm {
            get {
                return ResourceManager.GetString("CloseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Danger 的當地語系化字串。
        /// </summary>
        internal static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Instant Platinum&apos;s time will be the same, is easily identify by the PSN, we recommend manually modify time, even so do you wish to continue? 的當地語系化字串。
        /// </summary>
        internal static string DangerConfirm {
            get {
                return ResourceManager.GetString("DangerConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a M/d/yyyy h:mm:ss tt.
        /// </summary>
        internal static string DateFormatString {
            get {
                return ResourceManager.GetString("DateFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Trophy 的當地語系化字串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This trophy will have been be deleted, sure? 的當地語系化字串。
        /// </summary>
        internal static string DeleteTrophyConfirm {
            get {
                return ResourceManager.GetString("DeleteTrophyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &quot;{0}&quot; was not found. Please, select a valid trophy folder..
        /// </summary>
        internal static string FileNotFoundMsg {
            get {
                return ResourceManager.GetString("FileNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &quot;Minimum minutes&quot; can&apos;t be greater than &quot;Maximum minutes&quot;..
        /// </summary>
        internal static string MinCantBeGreaterThanMax {
            get {
                return ResourceManager.GetString("MinCantBeGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 no 的當地語系化字串。
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The last trophy synchronized with PSN has the following date: {0}. Select a date greater than this..
        /// </summary>
        internal static string PsnSyncTime {
            get {
                return ResourceManager.GetString("PsnSyncTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RandomEndTime 的當地語系化字串。
        /// </summary>
        internal static string RandomEndTime {
            get {
                return ResourceManager.GetString("RandomEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RandomStartTime 的當地語系化字串。
        /// </summary>
        internal static string RandomStartTime {
            get {
                return ResourceManager.GetString("RandomStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 please restart the program to apply the setting. 的當地語系化字串。
        /// </summary>
        internal static string RestartProgram {
            get {
                return ResourceManager.GetString("RestartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 To avoid the PSN identified,only not been synchronized trophy can be edited. 的當地語系化字串。
        /// </summary>
        internal static string SyncedTrophyCanNotEdit {
            get {
                return ResourceManager.GetString("SyncedTrophyCanNotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 yes 的當地語系化字串。
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
