name: .NET Core Desktop

on:
  push:
    branches: [ master, githubaction ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    env:
      Solution_Name: PS3TrophyIsGood.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: PS3TrophyIsGood
        path: PS3TrophyIsGood/bin/Release